apiVersion: v1
kind: Service
metadata:
  name: task-api
  namespace: task-manager
  labels:
    app: task-api
spec:
  selector:
    app: task-api
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
    - containerPort: 5000
    
